[[zones]]
id = "NZ"

[[zones]]
id = "Australia/Sydney"
name = "Sydney"

[[zones]]
id = "Asia/Kolkata"
name = "Bangalore"

[[zones]]
id = ""
name = "UTC"

[keymaps]
prev_minute = ["-"]
next_minute = ["+"]
zero_minute = ["0"]
prev_hour = ["h", "left"]
next_hour = ["l", "right"]
prev_day = ["k", "up"]
next_day = ["j", "down"]
prev_week = ["p", "<"]
next_week = ["n", ">"]
prev_line_select = [","]
next_line_select = ["."]
next_format_style = ["f"]
prev_format_style = ["F"]
next_zone_style = ["z"]
prev_zone_style = ["Z"]
toggle_date = ["d"]
open_web = ["o", "x"]
now = ["t"]
help = ["f1"]
quit = ["q", "esc", "ctrl+c"]
